services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: flightsdb
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: flights
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]

volumes:
  dbdata:
